exports.STATUS_ERR_UNKNOWN = 'Internal server error';
exports.STATUS_ERR_NO_DATA = 'No data found';
exports.STATUS_SUCCESS = 'success';
exports.STATUS_ERR_KNOWN_CODE = 100;
exports.STATUS_SUCCESS_CODE = 200;
exports.STATUS_ERR_UNKNOWN_CODE = 300;
exports.STATUS_ERR_DB = 'Database connection error';

exports.CHOICE_SINGLE = "CHOICE_SINGLE";
exports.CHOICE_MULTIPLE = "CHOICE_MULTIPLE";
exports.CHOICE_ASSERTION = "CHOICE_ASSERTION";
exports.CHOICE_BOOLEAN = "CHOICE_BOOLEAN";
exports.BLANKS_SINGLE = "BLANKS_SINGLE";
exports.BLANKS_MULTIPLE = "BLANKS_MULTIPLE";
exports.MATRIX_TYPE1 = "MATRIX_TYPE1";
exports.MATRIX_TYPE2 = "MATRIX_TYPE2";
exports.MATRIX_TYPE3 = "MATRIX_TYPE3";
//PAGINATION CONSTANT
exports.PAGINATION_DEFAULT_PAGE_SIZE = 10;
exports.PAGINATION_DEFAULT_MAX_PAGE_SIZE = 10000;
exports.PAGINATION_DEFAULT_PAGE_NUMBER = 1;

//  AWS
exports.AWS_ACCESS_KEY = "";
exports.AWS_SECRET_KEY = "";
exports.AWS_BUCKET = "";
